### ISSUE TITLE
this integration is not findable in the current HA

### ISSUE THREAD

**Issue by mannebk79** [wsdt/sensor.cryptoportfolio#2]
i cant find it in 

HACS
Addons
Integrations....

would be good to add to the readme, that the user could download the code from git via zip file, and with help of the samba addon one can copy the content to the config custom_component directory, that looks then like so:

![grafik](https://user-images.githubusercontent.com/60316272/221372224-0818955c-bf3a-44b5-8ec7-1a0c766795a7.png)

**Comment by wsdt** [comment]
yeah if I remember correctly, then you can manually upload this integration to use it

**Comment by mannebk79** [comment]
i was just adding that to the issue, so really its an issue with the readme here...

**Comment by wsdt** [comment]
added! thanks

**Comment by mannebk79** [comment]
and while your at it, the code for the sensors did change quite a bit.

here is an example from me with the 2.2023 HA version

I have seperated my configuration.yaml, so if you dont have that, you need to put each part into the respective area of your configurations.yaml with one more indentation than I have in this example.

sensors.yaml  (this is a sample BTC address... not my own!)
```
- platform: cryptoportfolio
  address: "1BMsHFczb2vY1BMDvFGWgGU8mkWVm5fupp"
  blockchain: "BTC"
  name: wallet-1
- platform: cryptoportfolio
  address: "1BMsHFczb2vY1BMDvFGWgGU8mkWVm5fupp"
  blockchain: "BTC"
  name: wallet-2
- platform: cryptoportfolio
  address: "1BMsHFczb2vY1BMDvFGWgGU8mkWVm5fupp"
  blockchain: "BTC"
  name: wallet-3
- platform: cryptoportfolio
  address: "1BMsHFczb2vY1BMDvFGWgGU8mkWVm5fupp"
  blockchain: "BTC"
  name: wallet-4
```

on top i got in the sensors.yaml the bitcoin extension from HA to pull some stuff to do some calculations later
```
- platform: bitcoin
  currency: EUR
  display_options:
    - exchangerate
    - market_price_usd
```

then in the templates.yaml i have
```
# callculate total of btc
- sensor:
  - name: "BTC Summe"
    unique_id: b591e62a-f9f5-49f1-9631-6dded399caf2
    unit_of_measurement: "BTC"
    state: "{{ states('sensor.wallet_1') |float + states('sensor.wallet_2') | float + states('sensor.wallet_3') | float + states('sensor.wallet_4') | float }}"
# callculate btc to EUR
- sensor:
  - name: "Crypto in Euro"
    unique_id: 26268704-8169-42e6-beb2-f68825fb94a3
    unit_of_measurement: "EUR"
    state: "{{ (states('sensor.wallet_1') |float + states('sensor.wallet_2') | float + states('sensor.wallet_3') | float + states('sensor.wallet_4') | float) * states('sensor.exchange_rate_1_btc') | float }}"
```

for lovelace i got this
```
type: entities
entities:
  - entity: sensor.exchange_rate_1_btc
  - entity: sensor.market_price
  - entity: sensor.wallet_1
  - entity: sensor.wallet_2
  - entity: sensor.wallet_3
  - entity: sensor.wallet_4
  - entity: sensor.btc_summe
  - entity: sensor.crypto_in_euro
```
and all that leads to the example lovelace output:
![grafik](https://user-images.githubusercontent.com/60316272/221372933-51436a24-930f-4cfa-a02a-a51c84271240.png)
